services:
  backend:
    build:
      context: back/
      dockerfile: Dockerfile
    env_file: .env
    environment:
      API_KEY: ${API_KEY}
    container_name: back
    ports:
      - "5000:5000"
    restart: always
    networks:
      - my_network

  frontend:
    build:
      context: front/
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "8080:8080"
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge